// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package eventschemas

import "encoding/json"
import "fmt"
import "reflect"

type SessionEventCaptured struct {
	// Environment corresponds to the JSON schema field "environment".
	Environment string `json:"environment" yaml:"environment" mapstructure:"environment"`

	// Payload corresponds to the JSON schema field "payload".
	Payload SessionEventCapturedPayload `json:"payload" yaml:"payload" mapstructure:"payload"`

	// ReleaseID corresponds to the JSON schema field "releaseId".
	ReleaseID string `json:"releaseId" yaml:"releaseId" mapstructure:"releaseId"`

	// SessionID corresponds to the JSON schema field "sessionId".
	SessionID string `json:"sessionId" yaml:"sessionId" mapstructure:"sessionId"`

	// Subtype corresponds to the JSON schema field "subtype".
	Subtype SessionEventCapturedSubtype `json:"subtype" yaml:"subtype" mapstructure:"subtype"`
}

type SessionEventCapturedPayload map[string]interface{}

type SessionEventCapturedSubtype string

const SessionEventCapturedSubtypeClick SessionEventCapturedSubtype = "Click"
const SessionEventCapturedSubtypeDOMMutation SessionEventCapturedSubtype = "DOMMutation"
const SessionEventCapturedSubtypeFormInput SessionEventCapturedSubtype = "FormInput"
const SessionEventCapturedSubtypeFullSnapshot SessionEventCapturedSubtype = "FullSnapshot"
const SessionEventCapturedSubtypeMouseMove SessionEventCapturedSubtype = "MouseMove"
const SessionEventCapturedSubtypeScroll SessionEventCapturedSubtype = "Scroll"
const SessionEventCapturedSubtypeViewportChange SessionEventCapturedSubtype = "ViewportChange"

var enumValues_SessionEventCapturedSubtype = []interface{}{
	"FullSnapshot",
	"DOMMutation",
	"MouseMove",
	"Click",
	"Scroll",
	"FormInput",
	"ViewportChange",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionEventCapturedSubtype) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SessionEventCapturedSubtype {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SessionEventCapturedSubtype, v)
	}
	*j = SessionEventCapturedSubtype(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionEventCaptured) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["environment"]; raw != nil && !ok {
		return fmt.Errorf("field environment in SessionEventCaptured: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in SessionEventCaptured: required")
	}
	if _, ok := raw["releaseId"]; raw != nil && !ok {
		return fmt.Errorf("field releaseId in SessionEventCaptured: required")
	}
	if _, ok := raw["sessionId"]; raw != nil && !ok {
		return fmt.Errorf("field sessionId in SessionEventCaptured: required")
	}
	if _, ok := raw["subtype"]; raw != nil && !ok {
		return fmt.Errorf("field subtype in SessionEventCaptured: required")
	}
	type Plain SessionEventCaptured
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SessionEventCaptured(plain)
	return nil
}
